import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BigNav from "@/components/custom/Navar/BigNav";
import Footer from "@/components/custom/Footer";
import MobileNav from "@/components/custom/Navar/SmallNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full  `}
      >
        <BigNav/>
        <MobileNav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
